# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: darleet
description: darleet
baseurl: ""
url: http://darleet.me

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: darleet
  description:
    - hello!
    - i am a second-year BMSTU student
    - and also a backend developer in 'ITS Tech'
    - feel free to contact me
  contact:
    email: darleet@mail.ru
    telegram: "@darl33t"
  profiles:
    vk: https://vk.com/darl33t
    github: https://github.com/darleet
    linkedin: https://www.linkedin.com/in/ivan-pavlov-ba225127b/
    stackoverflow: https://stackoverflow.com/users/13029632/darleet

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
